# Generated by Django 4.2.1 on 2023-11-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actualite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("auteur", models.CharField(max_length=100)),
                ("date_publication", models.DateField()),
                ("contenu", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Medicament",
            fields=[
                ("id_medicament", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("posologie", models.CharField(max_length=100)),
                ("date_expiration", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Pharmacie",
            fields=[
                ("id_pharmacie", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("heure_ouverture", models.TimeField()),
                ("heure_fermeture", models.TimeField()),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                ("id_utilisateur", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mot_de_passe", models.CharField(max_length=100)),
            ],
        ),
    ]
