# Generated by Django 4.2.1 on 2023-11-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MedecineApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicament",
            name="posologie",
        ),
        migrations.AddField(
            model_name="medicament",
            name="id_pharmacie",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="MedecineApp.pharmacie",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medicament",
            name="quantite",
            field=models.IntegerField(default=0),
        ),
    ]
