# Generated by Django 4.2.1 on 2023-11-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "MedecineApp",
            "0002_remove_medicament_posologie_medicament_id_pharmacie_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilisateur",
            name="email",
        ),
    ]
