# Generated by Django 4.2.1 on 2023-11-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MedecineApp", "0003_remove_utilisateur_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicament",
            name="id_pharmacie",
        ),
    ]
