# Generated by Django 4.2.1 on 2023-11-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MedecineApp", "0004_remove_medicament_id_pharmacie"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicament",
            name="id_pharmacie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="MedecineApp.pharmacie",
            ),
            preserve_default=False,
        ),
    ]
