# Generated by Django 4.2.1 on 2023-11-02 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MedecineApp", "0005_medicament_id_pharmacie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicament",
            name="id_pharmacie",
        ),
        migrations.AlterField(
            model_name="medicament",
            name="nom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="MedecineApp.pharmacie",
            ),
        ),
    ]
